name: Docs

on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.3.1

      - name: Commit changes to docs branch
        run: |
          git checkout docs --
          rm -r docs
          mv html docs
          git config --local user.email "docs_bot@github.com"
          git config --local user.name "docs_bot"
          git add docs
          git diff-index --quiet HEAD -- || git commit -m "Build docs"

      - name: Push to GitHub
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          branch: docs

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
