name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependency
        run: |
          sudo apt-get install libcrypto++-dev libcrypto++-doc libcrypto++-utils
          sudo npm install -g @bazel/bazelisk

      - name: Build
        run: make build

      - name: Test RSAEncrypter
        run: make run_test_encrypter
        working-directory: ./tests

      - name: Test PasswordEncrypter
        run: make run_test_passwordencrypter
        working-directory: ./tests

      - name: Test DataAccess
        run: make run_test_dataaccess
        working-directory: ./tests

      - name: Basic tests
        run: make run_test_basic
        working-directory: ./tests

      - name: Python tests
        run: make pytest_basic
        working-directory: ./tests
