name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependency
        run: |
          sudo apt-get install libcrypto++-dev libcrypto++-doc libcrypto++-utils
          sudo npm install -g @bazel/bazelisk

      - name: Run tests
        run: make test

      - name: Run googoe tests
        run: bazel test --test_output=all //:hello_test
        working-directory: ./tests
